[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.21"

[features]
resolution = true
skip-lint = false

[programs.localnet]
ballast = "HSSv351Q1DftJ7mgEzKm9rt41WUTyWZJZLXUq7sfqerr"

[provider]
cluster = "localnet"
wallet = ".keys/devnet/localnet.json"

[scripts]
test = "pnpm exec tsx tests/integration/program/run.ts"
