#!/usr/bin/env python3
"""Writes docs/demo.md — the video checklist — from evidence/proof-local/summary.json.

§35's end-to-end happy path is "both the integration test and the demo script": `pnpm proof:local`
runs it, and this maps each of its 12 rows to the signature that run produced, so every on-screen
transaction in the video has an explorer signature (§29) and the script cannot drift from the evidence.

    python3 scripts/proof/demo_checklist.py
"""

import json
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
summary = json.loads((REPO / "evidence/proof-local/summary.json").read_text())
proof = summary["proof"]
steps = proof["steps"]


def sig(prefix: str) -> str:
    """Signature of the first recorded step whose label starts with `prefix`."""
    for s in steps:
        if s["step"].startswith(prefix):
            return s["signature"]
    raise SystemExit(f"no step starting with {prefix!r} in summary.json — rerun pnpm proof:local")


def sigs(prefix: str) -> list[str]:
    return [s["signature"] for s in steps if s["step"].startswith(prefix)]


first = {v: next(x["signature"] for x in proof["sells"] if x["venue"] == v) for v in ("DLMM bid", "DAMM v2")}
keeper_off = next(c for c in summary["gate10"] if c["case"].startswith("keeper off"))
if not keeper_off["pass"]:
    sys.exit("gate 10's keeper-off redemption did not pass — the video cannot cite it; rerun pnpm proof:local")
redeem_sig = next((w for w in keeper_off["detail"].split() if re.fullmatch(r"[1-9A-HJ-NP-Za-km-z]{80,90}", w)), None)
if redeem_sig is None:
    sys.exit("gate 10's keeper-off redemption has no signature — rerun pnpm proof:local")

L = proof["launch"]
rows = [
    ("1", "`create_class` — the Proof config validated on-chain, prediction constant stored", sig("create_class"), "every §7 rule has its own error code"),
    ("2", "Launch: DBC pool + dust buy + DLMM pair + `transfer_pool_creator` + `register_launch` (D-011)", sig("launch"), f"prediction {proof['predicted']['solPerToken']:.4e} SOL/token recorded before any third-party trade"),
    ("3", "Buys to the threshold (three team wallets)", ", ".join(sigs("buy")), "curve completes at 10 SOL"),
    ("4", "`settle_graduation` — 15% migration fee + partner fees → vault (creator fees → `pay_creator`, D-022)", sig("settle_graduation"), f"migration fee {int(proof['graduation']['migrationFee']) / 1e9} SOL"),
    ("5", "`migration_damm_v2` — two permanently locked, PDA-owned positions", sig("migration_damm_v2"), "L fixed for good"),
    ("6", "`burn_leftover` — unsold supply burned", sig("burn_leftover"), "S final"),
    ("7", "`open` — whole vault as one DLMM bid at F's bin", sig("open"), f"F at open {proof['realisedAtOpen']['solPerToken']:.4e} SOL/token ({proof['realisedAtOpen']['vsPredictedPct']:+.2f}% vs prediction)"),
    ("8", "Sell pressure — each chunk to the better of the DLMM bid and DAMM v2", f"bid {first['DLMM bid']}, DAMM {first['DAMM v2']}", f"{proof['sellout']['transactions']} sells; lowest execution {proof['sellout']['lowestExecutionOverF']:.4f}·F"),
    ("9", "`refresh_floor` — cancel, burn the fills, F rises, re-place", sig("keeper: refresh_floor"), f"{len(sigs('keeper: refresh_floor'))} keeper refreshes during the sell-out"),
    ("10", "`redeem` — atomic: cancel, burn, pay F less 0.5%, re-place (keeper off)", redeem_sig, "exact payout = §10 formula"),
    ("11", "`harvest` (partner LP fees: 90% vault, 10% treasury) and `pay_creator`", f"{sig('harvest')}, {sig('pay_creator')}", f"F after sell-out {proof['afterSellout']['solPerToken']:.4e} SOL/token (not lower)"),
    ("12", "`ballast verify` — recompute everything from raw accounts", f"ballast verify {L} --rpc <url> --sellout …", "PASS" if proof["verifier"]["pass"] else "FAIL"),
]

out = [
    "# Demo checklist (§35 happy path → evidence)",
    "",
    "Generated by `scripts/proof/demo_checklist.py` from `evidence/proof-local/summary.json` "
    f"(run {summary['ranAt']}, cluster {summary.get('cluster', 'localnet')}). Every on-screen transaction "
    "needs its signature visible (§29); label any sped-up segment. The local validator runs Meteora's "
    "mainnet binaries (D-001); explorer links use a custom RPC URL.",
    "",
    "This is an executable buyback floor on Meteora, not a promise about prices elsewhere.",
    "",
    "| # | Step (§35) | Signature(s) | What the shot shows |",
    "|---|---|---|---|",
    *[f"| {n} | {what} | `{s}` | {note} |" for n, what, s, note in rows],
    "",
    "Also on screen: the token page for the launch (`/?launch=" + L + "`), showing F, the bid wall, the "
    "redemption quote and the six labelled prices; and `ballast scan` (94 of the 100 newest DBC → DAMM v2 "
    "launches had no permanently locked liquidity, `evidence/scanner/scan-100-2026-10-08.json`).",
    "",
    "Say on screen: late buyers can lose about 74%; F is in SOL; selling directly on DAMM v2 can execute "
    "below F, the bid and redemption cannot.",
    "",
]
(REPO / "docs/demo.md").write_text("\n".join(out))
print(f"docs/demo.md written ({len(rows)} rows)")
