//! Differential test: Rust must reproduce the Python reference's `s` for every vector (§11, §27).
//!
//! `vectors.json` is generated by `tests/reference/floor.py --emit 10000` and holds every §27
//! vector plus 10,000 random cases spread over the legal input box. CI fails on any mismatch.
//! The WASM leg of the same comparison lives in the `floor-wasm` package's test suite.
//!
//! Integers arrive as JSON *strings*: `s` and `l` run past IEEE-754's exact range, so a JSON
//! number would silently round and the test would compare the wrong values.

// Test arithmetic is not protocol arithmetic: an overflow here is a test failure, which is
// exactly what should happen. The lint stays on for `src/` (see lib.rs).
#![allow(clippy::arithmetic_side_effects)]

use ballast_floor::{floor_sqrt_q64, residual_sign, FloorInputs};
use std::cmp::Ordering;

const VECTORS: &str = include_str!("../vectors.json");

struct Case {
    name: String,
    kind: String,
    inputs: FloorInputs,
    expected_s: u128,
}

fn load() -> Vec<Case> {
    let doc: serde_json::Value = serde_json::from_str(VECTORS).expect("vectors.json parses");
    let cases = doc["cases"].as_array().expect("cases is an array");
    assert!(!cases.is_empty(), "vectors.json is empty");

    cases
        .iter()
        .map(|c| {
            let num = |k: &str| -> u128 {
                c[k].as_str()
                    .unwrap_or_else(|| panic!("{k} must be a string, not a JSON number"))
                    .parse()
                    .unwrap_or_else(|e| panic!("{k}: {e}"))
            };
            Case {
                name: c["name"].as_str().unwrap().to_owned(),
                kind: c["kind"].as_str().unwrap().to_owned(),
                inputs: FloorInputs {
                    v: num("v") as u64,
                    s: num("s_supply") as u64,
                    l: num("l"),
                    s_max: num("s_max"),
                },
                expected_s: num("s"),
            }
        })
        .collect()
}

/// The gate from §11: "Rust, WASM and Python must all produce identical `s` for every vector."
#[test]
fn rust_matches_python_reference_on_every_vector() {
    let cases = load();
    let mut mismatches = Vec::new();

    for case in &cases {
        match floor_sqrt_q64(&case.inputs) {
            Ok(got) if got == case.expected_s => {}
            Ok(got) => mismatches.push(format!(
                "{} ({}): expected {}, got {} (delta {})",
                case.name,
                case.kind,
                case.expected_s,
                got,
                got as i128 - case.expected_s as i128
            )),
            Err(e) => mismatches.push(format!(
                "{} ({}): expected {}, got error {:?} — inputs v={} s={} l={} s_max={}",
                case.name,
                case.kind,
                case.expected_s,
                e,
                case.inputs.v,
                case.inputs.s,
                case.inputs.l,
                case.inputs.s_max
            )),
        }
    }

    assert!(
        mismatches.is_empty(),
        "{} of {} vectors disagree with the Python reference:\n{}",
        mismatches.len(),
        cases.len(),
        mismatches
            .iter()
            .take(20)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );

    let spec = cases.iter().filter(|c| c.kind == "spec").count();
    assert!(spec >= 10, "expected every §27 vector, found {spec}");
    println!("{} vectors matched ({} from §27)", cases.len(), spec);
}

/// Independently of the expected values, every vector's `s` must be the exact floor of the root.
/// This catches a reference and an implementation that are wrong in the same way.
#[test]
fn every_vector_satisfies_the_defining_property() {
    for case in load() {
        let s = case.expected_s;
        assert_ne!(
            residual_sign(&case.inputs, s),
            Ordering::Greater,
            "{}: P(s) > 0",
            case.name
        );
        assert_eq!(
            residual_sign(&case.inputs, s + 1),
            Ordering::Greater,
            "{}: P(s+1) <= 0, so s is not the floor",
            case.name
        );
    }
}
