// @generated by codegen/gen.py from the vendored IDLs — do not edit.

/// Generated from `idl/dynamic_bonding_curve.json` (dynamic_bonding_curve 0.2.1, program `dbcij3LWUppWqq96dh6gJWwBifmcGfLSB5D4DuSMaqN`).
pub mod dbc {
    use bytemuck::{Pod, Zeroable};
    pub const PROGRAM_ID: &str = "dbcij3LWUppWqq96dh6gJWwBifmcGfLSB5D4DuSMaqN";
    pub const IDL_VERSION: &str = "0.2.1";

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct BaseFeeConfig {
        pub cliff_fee_numerator: u64,
        pub second_factor: u64,
        pub third_factor: u64,
        pub first_factor: u16,
        pub base_fee_mode: u8,
        pub padding_0: [u8; 5],
    }
    impl BaseFeeConfig {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 32;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[
            ("cliff_fee_numerator", 0),
            ("second_factor", 8),
            ("third_factor", 16),
            ("first_factor", 24),
            ("base_fee_mode", 26),
            ("padding_0", 27),
        ];
    }
    const _: () = assert!(core::mem::size_of::<BaseFeeConfig>() == 32);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct DynamicFeeConfig {
        pub initialized: u8,
        pub padding: [u8; 7],
        pub max_volatility_accumulator: u32,
        pub variable_fee_control: u32,
        pub bin_step: u16,
        pub filter_period: u16,
        pub decay_period: u16,
        pub reduction_factor: u16,
        pub padding2: [u8; 8],
        pub bin_step_u128: u128,
    }
    impl DynamicFeeConfig {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 48;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[
            ("initialized", 0),
            ("padding", 1),
            ("max_volatility_accumulator", 8),
            ("variable_fee_control", 12),
            ("bin_step", 16),
            ("filter_period", 18),
            ("decay_period", 20),
            ("reduction_factor", 22),
            ("padding2", 24),
            ("bin_step_u128", 32),
        ];
    }
    const _: () = assert!(core::mem::size_of::<DynamicFeeConfig>() == 48);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct PoolFeesConfig {
        pub base_fee: BaseFeeConfig,
        pub dynamic_fee: DynamicFeeConfig,
    }
    impl PoolFeesConfig {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 80;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] =
            &[("base_fee", 0), ("dynamic_fee", 32)];
    }
    const _: () = assert!(core::mem::size_of::<PoolFeesConfig>() == 80);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct LiquidityVestingInfo {
        pub is_initialized: u8,
        pub vesting_percentage: u8,
        pub _padding: [u8; 2],
        pub bps_per_period: u16,
        pub number_of_periods: u16,
        pub frequency: u32,
        pub cliff_duration_from_migration_time: u32,
    }
    impl LiquidityVestingInfo {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 16;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[
            ("is_initialized", 0),
            ("vesting_percentage", 1),
            ("_padding", 2),
            ("bps_per_period", 4),
            ("number_of_periods", 6),
            ("frequency", 8),
            ("cliff_duration_from_migration_time", 12),
        ];
    }
    const _: () = assert!(core::mem::size_of::<LiquidityVestingInfo>() == 16);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct LockedVestingConfig {
        pub amount_per_period: u64,
        pub cliff_duration_from_migration_time: u64,
        pub frequency: u64,
        pub number_of_period: u64,
        pub cliff_unlock_amount: u64,
        pub _padding: u64,
    }
    impl LockedVestingConfig {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 48;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[
            ("amount_per_period", 0),
            ("cliff_duration_from_migration_time", 8),
            ("frequency", 16),
            ("number_of_period", 24),
            ("cliff_unlock_amount", 32),
            ("_padding", 40),
        ];
    }
    const _: () = assert!(core::mem::size_of::<LockedVestingConfig>() == 48);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct LiquidityDistributionConfig {
        pub sqrt_price: u128,
        pub liquidity: u128,
    }
    impl LiquidityDistributionConfig {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 32;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] =
            &[("sqrt_price", 0), ("liquidity", 16)];
    }
    const _: () = assert!(core::mem::size_of::<LiquidityDistributionConfig>() == 32);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct PoolConfig {
        pub quote_mint: [u8; 32],
        pub fee_claimer: [u8; 32],
        pub leftover_receiver: [u8; 32],
        pub pool_fees: PoolFeesConfig,
        pub partner_liquidity_vesting_info: LiquidityVestingInfo,
        pub creator_liquidity_vesting_info: LiquidityVestingInfo,
        pub padding_0: [u8; 14],
        pub padding_1: u16,
        pub collect_fee_mode: u8,
        pub migration_option: u8,
        pub activation_type: u8,
        pub token_decimal: u8,
        pub version: u8,
        pub token_type: u8,
        pub quote_token_flag: u8,
        pub partner_permanent_locked_liquidity_percentage: u8,
        pub partner_liquidity_percentage: u8,
        pub creator_permanent_locked_liquidity_percentage: u8,
        pub creator_liquidity_percentage: u8,
        pub migration_fee_option: u8,
        pub fixed_token_supply_flag: u8,
        pub creator_trading_fee_percentage: u8,
        pub token_update_authority: u8,
        pub migration_fee_percentage: u8,
        pub creator_migration_fee_percentage: u8,
        pub padding_2: [u8; 7],
        pub swap_base_amount: u64,
        pub migration_quote_threshold: u64,
        pub migration_base_threshold: u64,
        pub migration_sqrt_price: u128,
        pub locked_vesting_config: LockedVestingConfig,
        pub pre_migration_token_supply: u64,
        pub post_migration_token_supply: u64,
        pub migrated_collect_fee_mode: u8,
        pub migrated_dynamic_fee: u8,
        pub migrated_pool_fee_bps: u16,
        pub migrated_pool_base_fee_mode: u8,
        pub enable_first_swap_with_min_fee: u8,
        pub migrated_compounding_fee_bps: u16,
        pub pool_creation_fee: u64,
        pub migrated_pool_base_fee_bytes: [u8; 16],
        pub sqrt_start_price: u128,
        pub curve: [LiquidityDistributionConfig; 20],
    }
    impl PoolConfig {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 1040;
        pub const DISCRIMINATOR: [u8; 8] = [26, 108, 14, 123, 116, 230, 129, 43];
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[
            ("quote_mint", 0),
            ("fee_claimer", 32),
            ("leftover_receiver", 64),
            ("pool_fees", 96),
            ("partner_liquidity_vesting_info", 176),
            ("creator_liquidity_vesting_info", 192),
            ("padding_0", 208),
            ("padding_1", 222),
            ("collect_fee_mode", 224),
            ("migration_option", 225),
            ("activation_type", 226),
            ("token_decimal", 227),
            ("version", 228),
            ("token_type", 229),
            ("quote_token_flag", 230),
            ("partner_permanent_locked_liquidity_percentage", 231),
            ("partner_liquidity_percentage", 232),
            ("creator_permanent_locked_liquidity_percentage", 233),
            ("creator_liquidity_percentage", 234),
            ("migration_fee_option", 235),
            ("fixed_token_supply_flag", 236),
            ("creator_trading_fee_percentage", 237),
            ("token_update_authority", 238),
            ("migration_fee_percentage", 239),
            ("creator_migration_fee_percentage", 240),
            ("padding_2", 241),
            ("swap_base_amount", 248),
            ("migration_quote_threshold", 256),
            ("migration_base_threshold", 264),
            ("migration_sqrt_price", 272),
            ("locked_vesting_config", 288),
            ("pre_migration_token_supply", 336),
            ("post_migration_token_supply", 344),
            ("migrated_collect_fee_mode", 352),
            ("migrated_dynamic_fee", 353),
            ("migrated_pool_fee_bps", 354),
            ("migrated_pool_base_fee_mode", 356),
            ("enable_first_swap_with_min_fee", 357),
            ("migrated_compounding_fee_bps", 358),
            ("pool_creation_fee", 360),
            ("migrated_pool_base_fee_bytes", 368),
            ("sqrt_start_price", 384),
            ("curve", 400),
        ];
    }
    const _: () = assert!(core::mem::size_of::<PoolConfig>() == 1040);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct VolatilityTracker {
        pub last_update_timestamp: u64,
        pub padding: [u8; 8],
        pub sqrt_price_reference: u128,
        pub volatility_accumulator: u128,
        pub volatility_reference: u128,
    }
    impl VolatilityTracker {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 64;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[
            ("last_update_timestamp", 0),
            ("padding", 8),
            ("sqrt_price_reference", 16),
            ("volatility_accumulator", 32),
            ("volatility_reference", 48),
        ];
    }
    const _: () = assert!(core::mem::size_of::<VolatilityTracker>() == 64);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct PoolMetrics {
        pub total_protocol_base_fee: u64,
        pub total_protocol_quote_fee: u64,
        pub total_trading_base_fee: u64,
        pub total_trading_quote_fee: u64,
    }
    impl PoolMetrics {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 32;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[
            ("total_protocol_base_fee", 0),
            ("total_protocol_quote_fee", 8),
            ("total_trading_base_fee", 16),
            ("total_trading_quote_fee", 24),
        ];
    }
    const _: () = assert!(core::mem::size_of::<PoolMetrics>() == 32);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct PoolState {
        pub volatility_tracker: VolatilityTracker,
        pub config: [u8; 32],
        pub creator: [u8; 32],
        pub base_mint: [u8; 32],
        pub base_vault: [u8; 32],
        pub quote_vault: [u8; 32],
        pub base_reserve: u64,
        pub quote_reserve: u64,
        pub protocol_base_fee: u64,
        pub protocol_quote_fee: u64,
        pub partner_base_fee: u64,
        pub partner_quote_fee: u64,
        pub sqrt_price: u128,
        pub activation_point: u64,
        pub pool_type: u8,
        pub is_migrated: u8,
        pub is_partner_withdraw_surplus: u8,
        pub is_protocol_withdraw_surplus: u8,
        pub migration_progress: u8,
        pub is_withdraw_leftover: u8,
        pub is_creator_withdraw_surplus: u8,
        pub migration_fee_withdraw_status: u8,
        pub metrics: PoolMetrics,
        pub finish_curve_timestamp: u64,
        pub creator_base_fee: u64,
        pub creator_quote_fee: u64,
        pub legacy_creation_fee_bits: u8,
        pub creation_fee_bits: u8,
        pub has_swap: u8,
        pub _padding_0: [u8; 5],
        pub protocol_liquidity_migration_fee_bps: u16,
        pub _padding_1: [u8; 6],
        pub protocol_migration_base_fee_amount: u64,
        pub protocol_migration_quote_fee_amount: u64,
        pub _padding_2: [u64; 3],
    }
    impl PoolState {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 416;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[
            ("volatility_tracker", 0),
            ("config", 64),
            ("creator", 96),
            ("base_mint", 128),
            ("base_vault", 160),
            ("quote_vault", 192),
            ("base_reserve", 224),
            ("quote_reserve", 232),
            ("protocol_base_fee", 240),
            ("protocol_quote_fee", 248),
            ("partner_base_fee", 256),
            ("partner_quote_fee", 264),
            ("sqrt_price", 272),
            ("activation_point", 288),
            ("pool_type", 296),
            ("is_migrated", 297),
            ("is_partner_withdraw_surplus", 298),
            ("is_protocol_withdraw_surplus", 299),
            ("migration_progress", 300),
            ("is_withdraw_leftover", 301),
            ("is_creator_withdraw_surplus", 302),
            ("migration_fee_withdraw_status", 303),
            ("metrics", 304),
            ("finish_curve_timestamp", 336),
            ("creator_base_fee", 344),
            ("creator_quote_fee", 352),
            ("legacy_creation_fee_bits", 360),
            ("creation_fee_bits", 361),
            ("has_swap", 362),
            ("_padding_0", 363),
            ("protocol_liquidity_migration_fee_bps", 368),
            ("_padding_1", 370),
            ("protocol_migration_base_fee_amount", 376),
            ("protocol_migration_quote_fee_amount", 384),
            ("_padding_2", 392),
        ];
    }
    const _: () = assert!(core::mem::size_of::<PoolState>() == 416);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct VirtualPool {
        pub pool_state: PoolState,
    }
    impl VirtualPool {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 416;
        pub const DISCRIMINATOR: [u8; 8] = [213, 224, 5, 209, 98, 69, 119, 92];
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[("pool_state", 0)];
    }
    const _: () = assert!(core::mem::size_of::<VirtualPool>() == 416);
}

/// Generated from `idl/cp_amm.json` (cp_amm 0.2.4, program `cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG`).
pub mod damm_v2 {
    use bytemuck::{Pod, Zeroable};
    pub const PROGRAM_ID: &str = "cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG";
    pub const IDL_VERSION: &str = "0.2.4";

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct BaseFeeInfo {
        pub data: [u8; 32],
    }
    impl BaseFeeInfo {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 32;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[("data", 0)];
    }
    const _: () = assert!(core::mem::size_of::<BaseFeeInfo>() == 32);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct BaseFeeStruct {
        pub base_fee_info: BaseFeeInfo,
        pub padding_1: u64,
    }
    impl BaseFeeStruct {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 40;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] =
            &[("base_fee_info", 0), ("padding_1", 32)];
    }
    const _: () = assert!(core::mem::size_of::<BaseFeeStruct>() == 40);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct DynamicFeeStruct {
        pub initialized: u8,
        pub padding: [u8; 7],
        pub max_volatility_accumulator: u32,
        pub variable_fee_control: u32,
        pub bin_step: u16,
        pub filter_period: u16,
        pub decay_period: u16,
        pub reduction_factor: u16,
        pub last_update_timestamp: u64,
        pub bin_step_u128: u128,
        pub sqrt_price_reference: u128,
        pub volatility_accumulator: u128,
        pub volatility_reference: u128,
    }
    impl DynamicFeeStruct {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 96;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[
            ("initialized", 0),
            ("padding", 1),
            ("max_volatility_accumulator", 8),
            ("variable_fee_control", 12),
            ("bin_step", 16),
            ("filter_period", 18),
            ("decay_period", 20),
            ("reduction_factor", 22),
            ("last_update_timestamp", 24),
            ("bin_step_u128", 32),
            ("sqrt_price_reference", 48),
            ("volatility_accumulator", 64),
            ("volatility_reference", 80),
        ];
    }
    const _: () = assert!(core::mem::size_of::<DynamicFeeStruct>() == 96);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct PoolFeesStruct {
        pub base_fee: BaseFeeStruct,
        pub protocol_fee_percent: u8,
        pub padding_0: u8,
        pub referral_fee_percent: u8,
        pub padding_1: [u8; 3],
        pub compounding_fee_bps: u16,
        pub dynamic_fee: DynamicFeeStruct,
        pub init_sqrt_price: u128,
    }
    impl PoolFeesStruct {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 160;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[
            ("base_fee", 0),
            ("protocol_fee_percent", 40),
            ("padding_0", 41),
            ("referral_fee_percent", 42),
            ("padding_1", 43),
            ("compounding_fee_bps", 46),
            ("dynamic_fee", 48),
            ("init_sqrt_price", 144),
        ];
    }
    const _: () = assert!(core::mem::size_of::<PoolFeesStruct>() == 160);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct PoolMetrics {
        pub total_lp_a_fee: u128,
        pub total_lp_b_fee: u128,
        pub total_protocol_a_fee: u64,
        pub total_protocol_b_fee: u64,
        pub padding_0: [u64; 2],
        pub total_position: u64,
        pub padding: u64,
    }
    impl PoolMetrics {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 80;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[
            ("total_lp_a_fee", 0),
            ("total_lp_b_fee", 16),
            ("total_protocol_a_fee", 32),
            ("total_protocol_b_fee", 40),
            ("padding_0", 48),
            ("total_position", 64),
            ("padding", 72),
        ];
    }
    const _: () = assert!(core::mem::size_of::<PoolMetrics>() == 80);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct RewardInfo {
        pub initialized: u8,
        pub reward_token_flag: u8,
        pub _padding_0: [u8; 6],
        pub dead_liquidity_reward_checkpoint: u64,
        pub mint: [u8; 32],
        pub vault: [u8; 32],
        pub funder: [u8; 32],
        pub reward_duration: u64,
        pub reward_duration_end: u64,
        pub reward_rate: u128,
        pub reward_per_token_stored: [u8; 32],
        pub last_update_time: u64,
        pub cumulative_seconds_with_empty_liquidity_reward: u64,
    }
    impl RewardInfo {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 192;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[
            ("initialized", 0),
            ("reward_token_flag", 1),
            ("_padding_0", 2),
            ("dead_liquidity_reward_checkpoint", 8),
            ("mint", 16),
            ("vault", 48),
            ("funder", 80),
            ("reward_duration", 112),
            ("reward_duration_end", 120),
            ("reward_rate", 128),
            ("reward_per_token_stored", 144),
            ("last_update_time", 176),
            ("cumulative_seconds_with_empty_liquidity_reward", 184),
        ];
    }
    const _: () = assert!(core::mem::size_of::<RewardInfo>() == 192);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct Pool {
        pub pool_fees: PoolFeesStruct,
        pub token_a_mint: [u8; 32],
        pub token_b_mint: [u8; 32],
        pub token_a_vault: [u8; 32],
        pub token_b_vault: [u8; 32],
        pub whitelisted_vault: [u8; 32],
        pub padding_0: [u8; 32],
        pub liquidity: u128,
        pub padding_1: u128,
        pub protocol_a_fee: u64,
        pub protocol_b_fee: u64,
        pub dead_liquidity_fee_checkpoint: u64,
        pub padding_2: [u8; 8],
        pub sqrt_min_price: u128,
        pub sqrt_max_price: u128,
        pub sqrt_price: u128,
        pub activation_point: u64,
        pub activation_type: u8,
        pub pool_status: u8,
        pub token_a_flag: u8,
        pub token_b_flag: u8,
        pub collect_fee_mode: u8,
        pub pool_type: u8,
        pub fee_version: u8,
        pub padding_3: u8,
        pub fee_a_per_liquidity: [u8; 32],
        pub fee_b_per_liquidity: [u8; 32],
        pub permanent_lock_liquidity: u128,
        pub metrics: PoolMetrics,
        pub creator: [u8; 32],
        pub token_a_amount: u64,
        pub token_b_amount: u64,
        pub layout_version: u8,
        pub padding_4: [u8; 7],
        pub padding_5: [u64; 3],
        pub reward_infos: [RewardInfo; 2],
    }
    impl Pool {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 1104;
        pub const DISCRIMINATOR: [u8; 8] = [241, 154, 109, 4, 17, 177, 109, 188];
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[
            ("pool_fees", 0),
            ("token_a_mint", 160),
            ("token_b_mint", 192),
            ("token_a_vault", 224),
            ("token_b_vault", 256),
            ("whitelisted_vault", 288),
            ("padding_0", 320),
            ("liquidity", 352),
            ("padding_1", 368),
            ("protocol_a_fee", 384),
            ("protocol_b_fee", 392),
            ("dead_liquidity_fee_checkpoint", 400),
            ("padding_2", 408),
            ("sqrt_min_price", 416),
            ("sqrt_max_price", 432),
            ("sqrt_price", 448),
            ("activation_point", 464),
            ("activation_type", 472),
            ("pool_status", 473),
            ("token_a_flag", 474),
            ("token_b_flag", 475),
            ("collect_fee_mode", 476),
            ("pool_type", 477),
            ("fee_version", 478),
            ("padding_3", 479),
            ("fee_a_per_liquidity", 480),
            ("fee_b_per_liquidity", 512),
            ("permanent_lock_liquidity", 544),
            ("metrics", 560),
            ("creator", 640),
            ("token_a_amount", 672),
            ("token_b_amount", 680),
            ("layout_version", 688),
            ("padding_4", 689),
            ("padding_5", 696),
            ("reward_infos", 720),
        ];
    }
    const _: () = assert!(core::mem::size_of::<Pool>() == 1104);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct PositionMetrics {
        pub total_claimed_a_fee: u64,
        pub total_claimed_b_fee: u64,
    }
    impl PositionMetrics {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 16;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] =
            &[("total_claimed_a_fee", 0), ("total_claimed_b_fee", 8)];
    }
    const _: () = assert!(core::mem::size_of::<PositionMetrics>() == 16);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct UserRewardInfo {
        pub reward_per_token_checkpoint: [u8; 32],
        pub reward_pendings: u64,
        pub total_claimed_rewards: u64,
    }
    impl UserRewardInfo {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 48;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[
            ("reward_per_token_checkpoint", 0),
            ("reward_pendings", 32),
            ("total_claimed_rewards", 40),
        ];
    }
    const _: () = assert!(core::mem::size_of::<UserRewardInfo>() == 48);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct InnerVesting {
        pub cliff_point: u64,
        pub period_frequency: u64,
        pub cliff_unlock_liquidity: u128,
        pub liquidity_per_period: u128,
        pub total_released_liquidity: u128,
        pub number_of_period: u16,
        pub padding: [u8; 14],
    }
    impl InnerVesting {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 80;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[
            ("cliff_point", 0),
            ("period_frequency", 8),
            ("cliff_unlock_liquidity", 16),
            ("liquidity_per_period", 32),
            ("total_released_liquidity", 48),
            ("number_of_period", 64),
            ("padding", 66),
        ];
    }
    const _: () = assert!(core::mem::size_of::<InnerVesting>() == 80);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct Position {
        pub pool: [u8; 32],
        pub nft_mint: [u8; 32],
        pub fee_a_per_token_checkpoint: [u8; 32],
        pub fee_b_per_token_checkpoint: [u8; 32],
        pub fee_a_pending: u64,
        pub fee_b_pending: u64,
        pub unlocked_liquidity: u128,
        pub vested_liquidity: u128,
        pub permanent_locked_liquidity: u128,
        pub metrics: PositionMetrics,
        pub reward_infos: [UserRewardInfo; 2],
        pub inner_vesting: InnerVesting,
        pub delegate_permission: u32,
        pub padding: [u8; 12],
    }
    impl Position {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 400;
        pub const DISCRIMINATOR: [u8; 8] = [170, 188, 143, 228, 122, 64, 247, 208];
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[
            ("pool", 0),
            ("nft_mint", 32),
            ("fee_a_per_token_checkpoint", 64),
            ("fee_b_per_token_checkpoint", 96),
            ("fee_a_pending", 128),
            ("fee_b_pending", 136),
            ("unlocked_liquidity", 144),
            ("vested_liquidity", 160),
            ("permanent_locked_liquidity", 176),
            ("metrics", 192),
            ("reward_infos", 208),
            ("inner_vesting", 304),
            ("delegate_permission", 384),
            ("padding", 388),
        ];
    }
    const _: () = assert!(core::mem::size_of::<Position>() == 400);
}

/// Generated from `idl/lb_clmm.json` (lb_clmm 0.12.0, program `LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo`).
pub mod dlmm {
    use bytemuck::{Pod, Zeroable};
    pub const PROGRAM_ID: &str = "LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo";
    pub const IDL_VERSION: &str = "0.12.0";

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct StaticParameters {
        pub base_factor: u16,
        pub filter_period: u16,
        pub decay_period: u16,
        pub reduction_factor: u16,
        pub variable_fee_control: u32,
        pub max_volatility_accumulator: u32,
        pub min_bin_id: i32,
        pub max_bin_id: i32,
        pub protocol_share: u16,
        pub base_fee_power_factor: u8,
        pub function_type: u8,
        pub collect_fee_mode: u8,
        pub _padding: [u8; 3],
    }
    impl StaticParameters {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 32;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[
            ("base_factor", 0),
            ("filter_period", 2),
            ("decay_period", 4),
            ("reduction_factor", 6),
            ("variable_fee_control", 8),
            ("max_volatility_accumulator", 12),
            ("min_bin_id", 16),
            ("max_bin_id", 20),
            ("protocol_share", 24),
            ("base_fee_power_factor", 26),
            ("function_type", 27),
            ("collect_fee_mode", 28),
            ("_padding", 29),
        ];
    }
    const _: () = assert!(core::mem::size_of::<StaticParameters>() == 32);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct VariableParameters {
        pub volatility_accumulator: u32,
        pub volatility_reference: u32,
        pub index_reference: i32,
        pub _padding: [u8; 4],
        pub last_update_timestamp: i64,
        pub _padding_1: [u8; 8],
    }
    impl VariableParameters {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 32;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[
            ("volatility_accumulator", 0),
            ("volatility_reference", 4),
            ("index_reference", 8),
            ("_padding", 12),
            ("last_update_timestamp", 16),
            ("_padding_1", 24),
        ];
    }
    const _: () = assert!(core::mem::size_of::<VariableParameters>() == 32);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct ProtocolFee {
        pub amount_x: u64,
        pub amount_y: u64,
    }
    impl ProtocolFee {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 16;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[("amount_x", 0), ("amount_y", 8)];
    }
    const _: () = assert!(core::mem::size_of::<ProtocolFee>() == 16);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct RewardInfo {
        pub mint: [u8; 32],
        pub vault: [u8; 32],
        pub funder: [u8; 32],
        pub reward_duration: u64,
        pub reward_duration_end: u64,
        pub reward_rate: u128,
        pub last_update_time: u64,
        pub cumulative_seconds_with_empty_liquidity_reward: u64,
    }
    impl RewardInfo {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 144;
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[
            ("mint", 0),
            ("vault", 32),
            ("funder", 64),
            ("reward_duration", 96),
            ("reward_duration_end", 104),
            ("reward_rate", 112),
            ("last_update_time", 128),
            ("cumulative_seconds_with_empty_liquidity_reward", 136),
        ];
    }
    const _: () = assert!(core::mem::size_of::<RewardInfo>() == 144);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct LbPair {
        pub parameters: StaticParameters,
        pub v_parameters: VariableParameters,
        pub bump_seed: [u8; 1],
        pub bin_step_seed: [u8; 2],
        pub pair_type: u8,
        pub active_id: i32,
        pub bin_step: u16,
        pub status: u8,
        pub require_base_factor_seed: u8,
        pub base_factor_seed: [u8; 2],
        pub activation_type: u8,
        pub creator_pool_on_off_control: u8,
        pub token_x_mint: [u8; 32],
        pub token_y_mint: [u8; 32],
        pub reserve_x: [u8; 32],
        pub reserve_y: [u8; 32],
        pub protocol_fee: ProtocolFee,
        pub _padding_1: [u8; 32],
        pub reward_infos: [RewardInfo; 2],
        pub oracle: [u8; 32],
        pub bin_array_bitmap: [u64; 16],
        pub last_updated_at: i64,
        pub _padding_2: [u8; 32],
        pub pre_activation_swap_address: [u8; 32],
        pub base_key: [u8; 32],
        pub activation_point: u64,
        pub pre_activation_duration: u64,
        pub _padding_3: [u8; 8],
        pub _padding_4: u64,
        pub creator: [u8; 32],
        pub token_mint_x_program_flag: u8,
        pub token_mint_y_program_flag: u8,
        pub version: u8,
        pub _reserved: [u8; 21],
    }
    impl LbPair {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 896;
        pub const DISCRIMINATOR: [u8; 8] = [33, 11, 49, 98, 181, 101, 177, 13];
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[
            ("parameters", 0),
            ("v_parameters", 32),
            ("bump_seed", 64),
            ("bin_step_seed", 65),
            ("pair_type", 67),
            ("active_id", 68),
            ("bin_step", 72),
            ("status", 74),
            ("require_base_factor_seed", 75),
            ("base_factor_seed", 76),
            ("activation_type", 78),
            ("creator_pool_on_off_control", 79),
            ("token_x_mint", 80),
            ("token_y_mint", 112),
            ("reserve_x", 144),
            ("reserve_y", 176),
            ("protocol_fee", 208),
            ("_padding_1", 224),
            ("reward_infos", 256),
            ("oracle", 544),
            ("bin_array_bitmap", 576),
            ("last_updated_at", 704),
            ("_padding_2", 712),
            ("pre_activation_swap_address", 744),
            ("base_key", 776),
            ("activation_point", 808),
            ("pre_activation_duration", 816),
            ("_padding_3", 824),
            ("_padding_4", 832),
            ("creator", 840),
            ("token_mint_x_program_flag", 872),
            ("token_mint_y_program_flag", 873),
            ("version", 874),
            ("_reserved", 875),
        ];
    }
    const _: () = assert!(core::mem::size_of::<LbPair>() == 896);

    #[repr(C, packed)]
    #[derive(Clone, Copy, Pod, Zeroable)]
    pub struct LimitOrder {
        pub lb_pair: [u8; 32],
        pub owner: [u8; 32],
        pub bin_count: u16,
        pub _padding_0: [u8; 14],
        pub padding_1: [u64; 4],
    }
    impl LimitOrder {
        /// Packed size; equals the on-chain account size minus the 8-byte discriminator.
        pub const SIZE: usize = 112;
        pub const DISCRIMINATOR: [u8; 8] = [137, 183, 212, 91, 115, 29, 141, 227];
        /// (field, offset within the struct) as computed by the generator.
        pub const OFFSETS: &'static [(&'static str, usize)] = &[
            ("lb_pair", 0),
            ("owner", 32),
            ("bin_count", 64),
            ("_padding_0", 66),
            ("padding_1", 80),
        ];
    }
    const _: () = assert!(core::mem::size_of::<LimitOrder>() == 112);
}
