//! Vendored zero-copy layouts of the deployed Meteora programs (§15 `crates/meteora-types`).
//!
//! Generated by `codegen/gen.py` from the IDLs in `idl/` (copied from the pinned SDKs:
//! DBC SDK 1.5.13 → `dynamic_bonding_curve` 0.2.1, cp-amm SDK 1.4.8 → `cp_amm` 0.2.4,
//! dlmm SDK 1.9.10 → `lb_clmm` 0.12.0). Every struct is `#[repr(C, packed)]` + `Pod`, so an
//! account decodes with `bytemuck::from_bytes(&data[8..])` after checking `DISCRIMINATOR`.
//!
//! Packed is correct only because the deployed structs carry no implicit padding. The tests
//! prove that against real accounts created by the mainnet binaries on the local validator
//! (STEP 3): size equality, generator offsets = compiler offsets, and field-by-field equality
//! with the SDK's own decoder on the same bytes.
#![no_std]
#![allow(clippy::all)]

mod generated;
pub use generated::*;

/// Decode a zero-copy account: checks the discriminator and exact size, then casts.
pub fn decode<'a, T: bytemuck::Pod>(data: &'a [u8], discriminator: &[u8; 8]) -> Option<&'a T> {
    if data.len() != 8 + core::mem::size_of::<T>() || &data[..8] != discriminator {
        return None;
    }
    Some(bytemuck::from_bytes(&data[8..]))
}
